import Airtable from 'airtable';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

type MenuItem = {
    name: string;
    price: string;
};

interface IProps {
    menu: MenuItem[];
}

export default function Home({ menu }: IProps) {
    console.log('render', menu);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App - is this live?</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <ul>
                    {menu.map(item => {
                        return <li key={item.name}>{item.name}</li>;
                    })}
                </ul>
            </main>
        </div>
    );
}

export async function getStaticProps() {
    const base = new Airtable({ apiKey: process.env.AIRTABLE_API_KEY }).base(
        'appVBKhhEICWCBOvJ'
    );

    const data = await base('Menu').select({ view: 'Grid view' }).firstPage();
    const menu = data
        .filter(record => Object.keys(record.fields).length !== 0)
        .map(record => {
            return {
                name: record.get('Name') as string,
                price: record.get('Price') as string
            };
        });
    return {
        props: { menu }
    };
}
